# Elasticsearch Services for School ERP SaaS
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-lb
  namespace: monitoring
  labels:
    app: elasticsearch
    service: load-balancer
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      name: rest
  type: ClusterIP
---
# Elasticsearch Index Template Setup Job
apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-setup
  namespace: monitoring
spec:
  template:
    spec:
      containers:
      - name: setup
        image: curlimages/curl:7.85.0
        command:
        - /bin/sh
        - -c
        - |
          # Wait for Elasticsearch to be ready
          until curl -s http://elasticsearch-lb:9200/_cluster/health; do
            echo "Waiting for Elasticsearch..."
            sleep 10
          done
          
          # Create ILM policy
          curl -X PUT "elasticsearch-lb:9200/_ilm/policy/school_erp_logs_policy" \
            -H 'Content-Type: application/json' \
            -d'{
              "policy": {
                "phases": {
                  "hot": {
                    "actions": {
                      "rollover": {
                        "max_size": "50gb",
                        "max_age": "1d"
                      }
                    }
                  },
                  "warm": {
                    "min_age": "7d",
                    "actions": {
                      "allocate": {
                        "number_of_replicas": 0
                      }
                    }
                  },
                  "delete": {
                    "min_age": "90d"
                  }
                }
              }
            }'
          
          # Create index template
          curl -X PUT "elasticsearch-lb:9200/_index_template/school_erp_logs" \
            -H 'Content-Type: application/json' \
            -d'{
              "index_patterns": ["school-erp-*"],
              "template": {
                "settings": {
                  "index.lifecycle.name": "school_erp_logs_policy",
                  "index.lifecycle.rollover_alias": "school-erp-logs",
                  "number_of_shards": 1,
                  "number_of_replicas": 1
                },
                "mappings": {
                  "properties": {
                    "@timestamp": {"type": "date"},
                    "tenant_id": {"type": "keyword"},
                    "service_name": {"type": "keyword"},
                    "log_level": {"type": "keyword"},
                    "message": {"type": "text"},
                    "user_id": {"type": "keyword"},
                    "request_id": {"type": "keyword"},
                    "response_time": {"type": "integer"}
                  }
                }
              }
            }'
          
          echo "Elasticsearch setup completed"
      restartPolicy: OnFailure
