# Kibana Deployment for School ERP SaaS Log Visualization
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: monitoring
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.17.9
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch-lb.monitoring.svc.cluster.local:9200
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch-lb.monitoring.svc.cluster.local:9200
        - name: SERVER_NAME
          value: kibana.monitoring.svc.cluster.local
        - name: SERVER_BASEPATH
          value: /kibana
        - name: SERVER_REWRITEBASEPATH
          value: "true"
        - name: XPACK_MONITORING_ENABLED
          value: "true"
        - name: XPACK_GRAPH_ENABLED
          value: "false"
        - name: XPACK_ML_ENABLED
          value: "false"
        - name: XPACK_REPORTING_ENABLED
          value: "true"
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        ports:
        - containerPort: 5601
        readinessProbe:
          httpGet:
            path: /kibana/app/kibana
            port: 5601
          initialDelaySeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /kibana/app/kibana
            port: 5601
          initialDelaySeconds: 20
          timeoutSeconds: 10
        volumeMounts:
        - name: kibana-config
          mountPath: /usr/share/kibana/config/kibana.yml
          subPath: kibana.yml
        - name: kibana-dashboards
          mountPath: /usr/share/kibana/dashboards
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config
      - name: kibana-dashboards
        configMap:
          name: kibana-dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: monitoring
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: monitoring
data:
  kibana.yml: |
    server.name: kibana
    server.host: "0.0.0.0"
    server.port: 5601
    server.basePath: "/kibana"
    server.rewriteBasePath: true
    
    elasticsearch.hosts: ["http://elasticsearch-lb.monitoring.svc.cluster.local:9200"]
    elasticsearch.pingTimeout: 1500
    elasticsearch.requestTimeout: 30000
    elasticsearch.startupTimeout: 5000
    
    # Monitoring
    monitoring.enabled: true
    monitoring.kibana.collection.enabled: true
    
    # Security (disabled for simplicity)
    xpack.security.enabled: false
    xpack.graph.enabled: false
    xpack.ml.enabled: false
    xpack.monitoring.enabled: true
    xpack.reporting.enabled: true
    
    # School ERP SaaS Specific Settings
    kibana.index: ".kibana-school-erp"
    kibana.defaultAppId: "discover"
    
    # Logging
    logging.dest: stdout
    logging.silent: false
    logging.quiet: false
    logging.verbose: false
---
# Kibana Dashboards ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-dashboards
  namespace: monitoring
data:
  school_erp_overview_dashboard.json: |
    {
      "version": "7.17.9",
      "objects": [
        {
          "id": "school-erp-overview",
          "type": "dashboard",
          "attributes": {
            "title": "School ERP SaaS - System Overview",
            "hits": 0,
            "description": "Overview dashboard for School ERP SaaS monitoring",
            "panelsJSON": "[{\"embeddableConfig\":{},\"gridData\":{\"x\":0,\"y\":0,\"w\":24,\"h\":15,\"i\":\"1\"},\"id\":\"log-levels-pie\",\"panelIndex\":\"1\",\"type\":\"visualization\",\"version\":\"7.17.9\"},{\"embeddableConfig\":{},\"gridData\":{\"x\":24,\"y\":0,\"w\":24,\"h\":15,\"i\":\"2\"},\"id\":\"tenant-activity-bar\",\"panelIndex\":\"2\",\"type\":\"visualization\",\"version\":\"7.17.9\"}]",
            "timeRestore": false,
            "timeTo": "now",
            "timeFrom": "now-24h",
            "refreshInterval": {
              "pause": false,
              "value": 30000
            },
            "kibanaSavedObjectMeta": {
              "searchSourceJSON": "{\"query\":{\"match_all\":{}},\"filter\":[]}"
            }
          }
        }
      ]
    }
---
# Kibana Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /kibana/$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: monitoring.school-erp-saas.local
    http:
      paths:
      - path: /kibana(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: kibana
            port:
              number: 5601
