# k8s/hpa.yaml - Horizontal Pod Autoscaler with advanced metrics

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: school-erp-hpa
  namespace: school-erp
  labels:
    app: school-erp
    component: hpa
  annotations:
    kubernetes.io/description: "HPA for School ERP API based on CPU, Memory, and custom metrics"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: school-erp-api
  
  minReplicas: 3
  maxReplicas: 20
  
  # Scaling Behavior
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutes
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60   # 1 minute
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 4
        periodSeconds: 30
      selectPolicy: Max
  
  # Metrics for scaling decisions
  metrics:
  # CPU utilization
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  # Memory utilization
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  # Custom metric: HTTP requests per second
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  
  # Custom metric: Response time
  - type: Pods
    pods:
      metric:
        name: http_request_duration_seconds
      target:
        type: AverageValue
        averageValue: "500m"  # 500ms
  
  # External metric: SQS queue length (if using message queues)
  - type: External
    external:
      metric:
        name: sqs_queue_length
        selector:
          matchLabels:
            queue: email-processing
      target:
        type: Value
        value: "10"

---
# Vertical Pod Autoscaler (VPA) for resource recommendations
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: school-erp-vpa
  namespace: school-erp
  labels:
    app: school-erp
    component: vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: school-erp-api
  
  updatePolicy:
    updateMode: "Auto"  # Auto, Recreate, or Off
  
  resourcePolicy:
    containerPolicies:
    - containerName: school-erp-api
      minAllowed:
        cpu: 500m
        memory: 512Mi
      maxAllowed:
        cpu: 4000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
    - containerName: nginx-proxy
      minAllowed:
        cpu: 50m
        memory: 64Mi
      maxAllowed:
        cpu: 500m
        memory: 512Mi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: school-erp-pdb
  namespace: school-erp
  labels:
    app: school-erp
    component: pdb
spec:
  minAvailable: 2  # Always keep at least 2 pods available
  selector:
    matchLabels:
      app: school-erp
      component: api
