# k8s/rbac.yaml - Kubernetes RBAC Configuration
apiVersion: v1
kind: ServiceAccount
metadata:
  name: school-erp-service-account
  namespace: school-erp
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/school-erp-app-service-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: school-erp-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: school-erp-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: school-erp-cluster-role
subjects:
- kind: ServiceAccount
  name: school-erp-service-account
  namespace: school-erp
---
# Namespace Role for enhanced security
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: school-erp
  name: school-erp-namespace-role
rules:
- apiGroups: [""]
  resources: ["pods/log", "pods/exec"]
  verbs: ["get", "list", "create"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: school-erp-namespace-binding
  namespace: school-erp
subjects:
- kind: ServiceAccount
  name: school-erp-service-account
  namespace: school-erp
roleRef:
  kind: Role
  name: school-erp-namespace-role
  apiGroup: rbac.authorization.k8s.io
