# k8s/secrets.yaml - Comprehensive secrets management

apiVersion: v1
kind: Secret
metadata:
  name: school-erp-app-secrets
  namespace: school-erp
  labels:
    app: school-erp
    component: secrets
    environment: production
  annotations:
    kubernetes.io/description: "Application secrets for School ERP"
type: Opaque
data:
  # JWT Secrets (Base64 encoded)
  JWT_ACCESS_SECRET: <base64-encoded-jwt-access-secret>
  JWT_REFRESH_SECRET: <base64-encoded-jwt-refresh-secret>
  
  # Database Connection
  MONGODB_URI: <base64-encoded-mongodb-connection-string>
  MONGO_ROOT_USERNAME: <base64-encoded-mongo-username>
  MONGO_ROOT_PASSWORD: <base64-encoded-mongo-password>
  
  # Redis Connection
  REDIS_URL: <base64-encoded-redis-url>
  REDIS_PASSWORD: <base64-encoded-redis-password>
  
  # AWS Credentials (if not using IAM roles)
  AWS_ACCESS_KEY_ID: <base64-encoded-aws-access-key>
  AWS_SECRET_ACCESS_KEY: <base64-encoded-aws-secret-key>
  
  # SMTP Configuration
  SMTP_HOST: <base64-encoded-smtp-host>
  SMTP_USER: <base64-encoded-smtp-username>
  SMTP_PASS: <base64-encoded-smtp-password>
  
  # External Service API Keys
  SENTRY_DSN: <base64-encoded-sentry-dsn>
  STRIPE_SECRET_KEY: <base64-encoded-stripe-secret>
  RAZORPAY_SECRET_KEY: <base64-encoded-razorpay-secret>

---
# TLS Certificate Secret for HTTPS
apiVersion: v1
kind: Secret
metadata:
  name: school-erp-tls-secret
  namespace: school-erp
  labels:
    app: school-erp
    component: tls
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-certificate>
  tls.key: <base64-encoded-private-key>

---
# Docker Registry Secret (if using private registry)
apiVersion: v1
kind: Secret
metadata:
  name: school-erp-registry-secret
  namespace: school-erp
  labels:
    app: school-erp
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64-encoded-docker-config>

---
# Service Account for AWS IAM integration
apiVersion: v1
kind: ServiceAccount
metadata:
  name: school-erp-service-account
  namespace: school-erp
  labels:
    app: school-erp
    component: service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/school-erp-eks-role
imagePullSecrets:
- name: school-erp-registry-secret
