# k8s/vault/external-secrets.yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: school-erp
  labels:
    app: school-erp
    component: secrets
spec:
  provider:
    vault:
      server: "https://vault.your-domain.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "school-erp-role"
          serviceAccountRef:
            name: "school-erp-service-account"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: school-erp-app-secrets
  namespace: school-erp
  labels:
    app: school-erp
    component: secrets
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: school-erp-app-secrets
    creationPolicy: Owner
  data:
  - secretKey: JWT_ACCESS_SECRET
    remoteRef:
      key: school-erp/api
      property: jwt_access_secret
  - secretKey: JWT_REFRESH_SECRET
    remoteRef:
      key: school-erp/api
      property: jwt_refresh_secret
  - secretKey: MONGODB_URI
    remoteRef:
      key: school-erp/database
      property: mongodb_uri
  - secretKey: REDIS_URL
    remoteRef:
      key: school-erp/cache
      property: redis_url
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: school-erp/aws
      property: access_key_id
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: school-erp/aws
      property: secret_access_key
  - secretKey: CLOUDINARY_API_SECRET
    remoteRef:
      key: school-erp/cloudinary
      property: api_secret
  - secretKey: SENTRY_DSN
    remoteRef:
      key: school-erp/monitoring
      property: sentry_dsn

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-service-account
  namespace: school-erp
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "school-erp-role"
